### ISSUE TITLE
problem in finding variants

### ISSUE THREAD

**Issue by mital14** [CTrierMaansson/ALKfusiondiscover#2]
> find_variants(file = test_bam, genome="hg38")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘readGAlignments’ for signature ‘"list"’

**Comment by CTrierMaansson** [comment]
How do you get this error?
What is test_bam
Did you load your BAM into R somehow
find_variants() takes the raw BAM file, so you should use the name of the bam file

**Comment by CTrierMaansson** [comment]
> > find_variants(file = test_bam, genome="hg38")
> > Error in (function (classes, fdef, mtable)  :
> > unable to find an inherited method for function ‘readGAlignments’ for signature ‘"list"’

How do you get this error?
What is test_bam?
Did you load your BAM into R somehow?
find_variants() takes the raw BAM file, so you should use the name of the bam file such as "test_bam.bam"

**Comment by mital14** [comment]
Thanks for the reply, class of my bam was showing list,
i loaded bam and now getting empty file

> test_bam <- "/test_bam/2341_lb.bam"
> class(test_bam)
[1] "character"
> find_variants(file=test_bam,genome="hg19")
[1] "No ALK-EML4 was detected"
> test_bam_galn <-  EML4_ALK_detection(file = test_bam, genome = "hg19", mates = 2) 
> head(test_bam_galn)
GAlignments object with 0 alignments and 0 metadata columns:
   seqnames strand       cigar    qwidth     start       end     width     njunc
      <Rle>  <Rle> <character> <integer> <integer> <integer> <integer> <integer>
  -------
  seqinfo: no sequences

where am i mistaking?

**Comment by CTrierMaansson** [comment]
> Thanks for the reply, class of my bam was showing list, i loaded bam and now getting empty file
> 
> > test_bam <- "/test_bam/2341_lb.bam"
> > class(test_bam)
> > [1] "character"
> > find_variants(file=test_bam,genome="hg19")
> > [1] "No ALK-EML4 was detected"
> > test_bam_galn <-  EML4_ALK_detection(file = test_bam, genome = "hg19", mates = 2)
> > head(test_bam_galn)
> > GAlignments object with 0 alignments and 0 metadata columns:
> > seqnames strand       cigar    qwidth     start       end     width     njunc
> 
> seqinfo: no sequences
> 
> where am i mistaking?

Based on this DNAfusion cannot detect any gene fusion. Are you sure the sequenced DNA contains EML4-ALK? Have you aligned your reads to hg19 and not hg38?

**Comment by mital14** [comment]
I am not sure abouth the fusion it is consist of yet, but my concern here is why seqinfo shows no sequences? any help?

**Comment by CTrierMaansson** [comment]
> I am not sure abouth the fusion it is consist of yet, but my concern here is why seqinfo shows no sequences? any help?

If seqinfo shows no sequences it means DNAfusion does not detect any gene fusions. DNAfusion is only designed to detect specific gene fusions but cannot discover all/novel gene fusions. For this I would recommend using FACTERA (https://academic.oup.com/bioinformatics/article/30/23/3390/206958?login=true)

**Comment by mital14** [comment]
Thanks this was a great help!
